import React from "react";
import "../Styles/Components.css";
import "../Styles/Home.css";

function About() {
  return (
    <div className="App">
      <header className="App-header">
        <h1>About</h1>
        <p>
          Hello, I'm a software developer and a student at the University of
          Waterloo. I'm currently looking for a full-time position as a software
          developer. I'm passionate about software development and I'm always
          looking to learn new things. I'm also a huge fan of the anime series,
          Dragon Ball Z.
        </p>
        <p>And honestly that was all generated by GitHub-Copilot :D</p>
      </header>
    </div>
  );
}

export default About;
